package Interfaz;

import ficherosSeparados.Cifrar;
import ficherosSeparados.Descifrar;
import java.io.File;
import javax.swing.JFileChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Javier Gonzalez Rives
 */
public class encriptarGrafico extends javax.swing.JDialog {
    /**
     * Creates new form encriptarGrafico
     */
    public encriptarGrafico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rd128.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rd128 = new javax.swing.JRadioButton();
        rd256 = new javax.swing.JRadioButton();
        rd3des = new javax.swing.JRadioButton();
        txDirectorio = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        btCifrar = new javax.swing.JButton();
        btDesencriptar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txClave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(rd128);
        rd128.setText("AES128");

        buttonGroup1.add(rd256);
        rd256.setText("AES256");
        rd256.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd256ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rd3des);
        rd3des.setText("3DES");

        btBuscar.setText("buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btCifrar.setText("encriptar");
        btCifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCifrarActionPerformed(evt);
            }
        });

        btDesencriptar.setText("desencriptar");
        btDesencriptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDesencriptarActionPerformed(evt);
            }
        });

        btSalir.setText("salir");

        jLabel1.setFont(new java.awt.Font("Chilanka", 0, 18)); // NOI18N
        jLabel1.setText("Encriptar Desencriptar chachi guay");

        jLabel2.setText("Clave");

        txClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txClaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rd128)
                                .addGap(18, 18, 18)
                                .addComponent(btBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rd256)
                                    .addComponent(rd3des))
                                .addGap(18, 18, 18)
                                .addComponent(txDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCifrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDesencriptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSalir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txClave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rd128)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rd256)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rd3des)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCifrar)
                    .addComponent(btDesencriptar)
                    .addComponent(btSalir))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rd256ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd256ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd256ActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int resultado = fileChooser.showOpenDialog(this);
        // Comprobacion que la seleccionde del fichero es correcta
        if(resultado == JFileChooser.APPROVE_OPTION){
            // se almacena en el recuadro el directorio seleccionado
            txDirectorio.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btCifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCifrarActionPerformed
        int seleccion = 0;
        // switch que cambia segun el radio button
        if(rd128.isSelected()){
            seleccion = 1;
        }else if(rd256.isSelected()){
            seleccion = 2;
        }else{
            seleccion = 3;
        }
        // comprovacion de que el directorio no esta vacio
        if(!txDirectorio.getText().isEmpty()){
            File ficheroEntrada, ficheroSalida;
            ficheroEntrada = new File(txDirectorio.getText());
            String aux = ficheroEntrada.getAbsolutePath() + ".cod";
            ficheroSalida = new File(aux);
            String clave = txClave.getText().trim();
            Cifrar.cifrarFichero(ficheroEntrada, ficheroSalida, clave, seleccion);
        }
    }//GEN-LAST:event_btCifrarActionPerformed

    private void txClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txClaveActionPerformed

    private void btDesencriptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDesencriptarActionPerformed
       int seleccion = 0;
        // switch que cambia segun el radio button
        if(rd128.isSelected()){
            seleccion = 1;
        }else if(rd256.isSelected()){
            seleccion = 2;
        }else{
            seleccion = 3;
        }
        // comprovacion de que el directorio no esta vacio
        if(!txDirectorio.getText().isEmpty()){
            File ficheroEntrada, ficheroSalida;
            ficheroEntrada = new File(txDirectorio.getText());
            String aux = ficheroEntrada.getAbsolutePath().replace(".cod", "");
            ficheroSalida = new File(aux);
            String clave = txClave.getText().trim();
            Descifrar.descifrarFichero(ficheroEntrada, ficheroSalida, clave, seleccion);
        }
    }//GEN-LAST:event_btDesencriptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(encriptarGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(encriptarGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(encriptarGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(encriptarGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                encriptarGrafico dialog = new encriptarGrafico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCifrar;
    private javax.swing.JButton btDesencriptar;
    private javax.swing.JButton btSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton rd128;
    private javax.swing.JRadioButton rd256;
    private javax.swing.JRadioButton rd3des;
    private javax.swing.JTextField txClave;
    private javax.swing.JTextField txDirectorio;
    // End of variables declaration//GEN-END:variables
}
